version: '3'
services:
  nginx-stand-autoconfig:
    image: nginx-stand-autoconfig
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 80
      HOST_SUFFIX: dev.mik32.ru
      VIRTUAL_HOST: nginx-stand-autoconfig.dev.mik32.ru
    volumes:
      - /var/www/devops/nginx/conf.d:/etc/nginx/conf.d
      - /var/www/devops/nginx/docker-compose.yml:/var/nginx/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: "nginx-stand-autoconfig.mik32.127.0.0.1.nip.io"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev
networks:
  dev:
    external: true
    name: mik32
